sudo: false
language: python
python:
- '3.7'
jdk: oraclejdk8
cache:
  directories:
  - cache
  - dependencies
  - pip
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
  - pip install -r requirements.txt

script:
  - travis_wait ./gradlew buildPlugin test jacocoTestReport
  - python scripts/build_changelog.py
  - mkdocs build --verbose --clean --strict
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/
after_success:
    - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases

    api_key:
        secure: ''
    file: build/distributions/poetry-pycharm-plugin.zip
    skip_cleanup: true
    on:
        repo: koxudaxi/poetry-pycharm-plugin
        tags: on
#  - provider: script
#    api_key:
#    script: 'curl --fail --header "Authorization: Bearer ${JETBRAINS_TOKEN}" -F pluginId= -F file=@build/distributions/poetry-pycharm-plugin.zip https://plugins.jetbrains.com/plugin/uploadPlugin'
#    skip_cleanup: true
#    on:
#        repo: koxudaxi/poetry-pycharm-plugin
#        tags: on

  - provider: pages
    skip_cleanup: true
    github_token:
      secure: ''
    local_dir: site
    on:
      branch: master
      python: '3.7'
