site_name: Poetry PyCharm Plugin
site_description: A JetBrains PyCharm plugin for poetry.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: 🔗

repo_name: koxudaxi/poetry-pycharm-plugin
repo_url: https://github.com/koxudaxi/poetry-pycharm-plugin

google_analytics:
    - 'UA-142130505-1'
    - 'auto'

nav:
    - Overview: index.md
    - Install: install.md
    - Development: development.md
    - Changelog: changelog.md

plugins:
  - search