name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build-n-publish:
    name: Build and publish plugin 📦 to JetBrains merket
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: test 
      run: ./gradlew buildPlugin test jacocoTestReport
    - name: Publish a plugin
      run: |
         curl --fail --header "Authorization: Bearer ${{secrets.JETBRAINS_TOKEN}}" \ 
               -F pluginId= -F file=@build/distributions/poetry-pycharm-plugin.zip \
                https://plugins.jetbrains.com/plugin/uploadPlugin'
